FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir \
    google-cloud-pubsub==2.23.0 \
    google-cloud-bigquery==3.25.0

COPY local/pubsub_bq_sink.py .

CMD ["python", "pubsub_bq_sink.py"]
