"""
Local dev seed — inserts fixture events into the Firestore emulator.

Targets the `eventos` collection that the backend reads (see
backend/portal-api/app/api/v1/endpoints/events.py:8). Events carry the same
field names that the real ingestion pipeline produces
(see ingestion/pipeline_batch_ingestion.py), so the portal renders the same
shapes as in production.

Idempotent — documents are keyed by event id and written with merge=True.
"""

import json
import os
import socket
import time
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import firebase_admin
from firebase_admin import credentials, firestore

PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "demo-local")
COLLECTION = os.environ.get("FIRESTORE_EVENTS_COLLECTION", "eventos")
EVENTS_EXPORT_PATH = os.environ.get("EVENTS_EXPORT_PATH")


EVENTS: list[dict] = [
    # ── Multi-occurrence: Hamlet — Teatro Español (May 7–16, different times) ────
    # Tests schedule grouping: same name+venue across many days/times.
    {
        "id": "evt-hamlet-espanol-may07-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-07",
        "hora": "20:30",
        "fecha_utc": "2026-05-07T18:30:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may08-mat",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-08",
        "hora": "18:00",
        "fecha_utc": "2026-05-08T16:00:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may08-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-08",
        "hora": "20:30",
        "fecha_utc": "2026-05-08T18:30:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may09-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-09",
        "hora": "20:30",
        "fecha_utc": "2026-05-09T18:30:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may10-mat",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-10",
        "hora": "18:00",
        "fecha_utc": "2026-05-10T16:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may10-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-10",
        "hora": "20:30",
        "fecha_utc": "2026-05-10T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may11-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-11",
        "hora": "20:30",
        "fecha_utc": "2026-05-11T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may12-mat",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-12",
        "hora": "18:00",
        "fecha_utc": "2026-05-12T16:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may12-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-12",
        "hora": "20:30",
        "fecha_utc": "2026-05-12T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may13-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-13",
        "hora": "20:30",
        "fecha_utc": "2026-05-13T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may14-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-14",
        "hora": "20:30",
        "fecha_utc": "2026-05-14T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may15-mat",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-15",
        "hora": "18:00",
        "fecha_utc": "2026-05-15T16:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-hamlet-espanol-may16-eve",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-16",
        "hora": "20:30",
        "fecha_utc": "2026-05-16T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    # ── Multi-occurrence: Jazz al Palau — Palau Música Barcelona (May 8–14) ──────
    {
        "id": "evt-palau-jazz-may08",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-08",
        "hora": "19:00",
        "fecha_utc": "2026-05-08T17:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may09",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-09",
        "hora": "19:00",
        "fecha_utc": "2026-05-09T17:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may10",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-10",
        "hora": "19:00",
        "fecha_utc": "2026-05-10T17:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may10-late",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-10",
        "hora": "21:30",
        "fecha_utc": "2026-05-10T19:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may11",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-11",
        "hora": "19:00",
        "fecha_utc": "2026-05-11T17:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may12",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-12",
        "hora": "19:00",
        "fecha_utc": "2026-05-12T17:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may13",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-13",
        "hora": "19:00",
        "fecha_utc": "2026-05-13T17:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-palau-jazz-may14",
        "nombre": "Jazz al Palau — Temporada Primavera",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-14",
        "hora": "19:00",
        "fecha_utc": "2026-05-14T17:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-cat",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz-season",
        "artista_nombre": "Various Jazz Artists",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz-season/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-season-event/800/450",
        "promotor": "Palau Live",
    },
    # ── Multi-occurrence: Flamenco Sevilla — 3 shows/day (May 9–13) ──────────────
    {
        "id": "evt-flamenco-sev-may09-early",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-09",
        "hora": "20:00",
        "fecha_utc": "2026-05-09T18:00:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may09-late",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-09",
        "hora": "22:30",
        "fecha_utc": "2026-05-09T20:30:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may10-early",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-10",
        "hora": "20:00",
        "fecha_utc": "2026-05-10T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may10-late",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-10",
        "hora": "22:30",
        "fecha_utc": "2026-05-10T20:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may11-early",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-11",
        "hora": "20:00",
        "fecha_utc": "2026-05-11T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may11-late",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-11",
        "hora": "22:30",
        "fecha_utc": "2026-05-11T20:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may12-early",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-12",
        "hora": "20:00",
        "fecha_utc": "2026-05-12T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may12-late",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-12",
        "hora": "22:30",
        "fecha_utc": "2026-05-12T20:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may13-early",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-13",
        "hora": "20:00",
        "fecha_utc": "2026-05-13T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    {
        "id": "evt-flamenco-sev-may13-late",
        "nombre": "Flamenco en Sevilla — Casa Anselma",
        "url": "https://www.casaanselma.com/",
        "fecha": "2026-05-13",
        "hora": "22:30",
        "fecha_utc": "2026-05-13T20:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-anselma",
        "recinto_nombre": "Casa Anselma",
        "ciudad": "Sevilla",
        "direccion": "Calle Pagés del Corro, 49, 41010 Sevilla",
        "latitud": 37.3822,
        "longitud": -6.0023,
        "artista_id": "art-anselma-flamenco",
        "artista_nombre": "Casa Anselma",
        "artista_imagen": "https://picsum.photos/seed/anselma-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/anselma-flamenco-event/800/450",
        "promotor": "Casa Anselma",
    },
    # ── May 7 (past) ─────────────────────────────────────────────────────────────
    {
        "id": "evt-may07-madrid-pop",
        "nombre": "Pop Clásico — Teatro Barceló",
        "url": "https://www.teatrobarcelo.com/",
        "fecha": "2026-05-07",
        "hora": "21:00",
        "fecha_utc": "2026-05-07T19:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Pop",
        "subgenero": "Classic Pop",
        "recinto_id": "rec-barcelo",
        "recinto_nombre": "Teatro Barceló",
        "ciudad": "Madrid",
        "direccion": "Calle de Barceló, 11, 28004 Madrid",
        "latitud": 40.4272,
        "longitud": -3.6994,
        "artista_id": "art-barcelo-pop",
        "artista_nombre": "Mecano Tribute",
        "artista_imagen": "https://picsum.photos/seed/barcelo-pop/400/400",
        "imagen_evento": "https://picsum.photos/seed/barcelo-pop-event/800/450",
        "promotor": "Barceló Live",
    },
    {
        "id": "evt-may07-bcn-sports",
        "nombre": "Barça vs Atlético — LaLiga Jornada 36",
        "url": "https://www.fcbarcelona.com/",
        "fecha": "2026-05-07",
        "hora": "20:00",
        "fecha_utc": "2026-05-07T18:00:00Z",
        "estado": "offsale",
        "segmento": "Sports",
        "genero": "Soccer",
        "subgenero": "La Liga",
        "recinto_id": "rec-spotify-camp-nou",
        "recinto_nombre": "Spotify Camp Nou",
        "ciudad": "Barcelona",
        "direccion": "Carrer d'Arístides Maillol, s/n, 08028 Barcelona",
        "latitud": 41.3809,
        "longitud": 2.1228,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": "https://picsum.photos/seed/campnou-laliga-event/800/450",
        "promotor": "LaLiga",
    },
    # ── May 8 (past) ─────────────────────────────────────────────────────────────
    {
        "id": "evt-may08-madrid-theatre",
        "nombre": "Hamlet — Teatro Español",
        "url": "https://www.teatroespanol.es/",
        "fecha": "2026-05-08",
        "hora": "20:30",
        "fecha_utc": "2026-05-08T18:30:00Z",
        "estado": "offsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatro-espanol",
        "recinto_nombre": "Teatro Español",
        "ciudad": "Madrid",
        "direccion": "Calle del Príncipe, 25, 28012 Madrid",
        "latitud": 40.4144,
        "longitud": -3.7003,
        "artista_id": "art-hamlet-espanol",
        "artista_nombre": "Compañía Nacional de Teatro",
        "artista_imagen": "https://picsum.photos/seed/hamlet-espanol/400/400",
        "imagen_evento": "https://picsum.photos/seed/hamlet-espanol-event/800/450",
        "promotor": "Teatro Español",
    },
    {
        "id": "evt-may08-valencia-electronic",
        "nombre": "Techno Friday — Sala Ultramar",
        "url": "https://www.salaultramar.com/",
        "fecha": "2026-05-08",
        "hora": "23:30",
        "fecha_utc": "2026-05-08T21:30:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Techno",
        "recinto_id": "rec-ultramar",
        "recinto_nombre": "Sala Ultramar",
        "ciudad": "Valencia",
        "direccion": "Carrer del Progrés, 95, 46024 Valencia",
        "latitud": 39.4601,
        "longitud": -0.3322,
        "artista_id": "art-ultramar-techno",
        "artista_nombre": "Blawan",
        "artista_imagen": "https://picsum.photos/seed/ultramar-techno/400/400",
        "imagen_evento": "https://picsum.photos/seed/ultramar-techno-event/800/450",
        "promotor": "Ultramar Booking",
    },
    {
        "id": "evt-may08-sevilla-family",
        "nombre": "Mágico Viernes — Teatro Alhambra",
        "url": "https://www.teatroalhambradesevilla.com/",
        "fecha": "2026-05-08",
        "hora": "12:00",
        "fecha_utc": "2026-05-08T10:00:00Z",
        "estado": "offsale",
        "segmento": "Family",
        "genero": "Kids",
        "subgenero": "Magic",
        "recinto_id": "rec-alhambra-sev",
        "recinto_nombre": "Teatro Alhambra",
        "ciudad": "Sevilla",
        "direccion": "Calle Zaragoza, 33, 41001 Sevilla",
        "latitud": 37.3899,
        "longitud": -5.9941,
        "artista_id": "art-magico-sev",
        "artista_nombre": "Mago Ilusio",
        "artista_imagen": "https://picsum.photos/seed/magico-sev/400/400",
        "imagen_evento": "https://picsum.photos/seed/magico-sev-event/800/450",
        "promotor": "Alhambra Kids",
    },
    # ── May 9 (past) ─────────────────────────────────────────────────────────────
    {
        "id": "evt-may09-madrid-electronic",
        "nombre": "Saturday Night — Sala But",
        "url": "https://www.salagut.com/",
        "fecha": "2026-05-09",
        "hora": "00:00",
        "fecha_utc": "2026-05-08T22:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "House",
        "recinto_id": "rec-sala-but",
        "recinto_nombre": "Sala But",
        "ciudad": "Madrid",
        "direccion": "Calle de Barceló, 11, 28004 Madrid",
        "latitud": 40.4272,
        "longitud": -3.6994,
        "artista_id": "art-but-house",
        "artista_nombre": "Dixon",
        "artista_imagen": "https://picsum.photos/seed/but-house/400/400",
        "imagen_evento": "https://picsum.photos/seed/but-house-event/800/450",
        "promotor": "But Booking",
    },
    {
        "id": "evt-may09-bcn-jazz",
        "nombre": "Jazz al Palau — Sábado de Cámara",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-05-09",
        "hora": "19:00",
        "fecha_utc": "2026-05-09T17:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-palau-musica-bcn",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-palau-jazz",
        "artista_nombre": "Brad Mehldau Trio",
        "artista_imagen": "https://picsum.photos/seed/palau-jazz/400/400",
        "imagen_evento": "https://picsum.photos/seed/palau-jazz-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-may09-bilbao-rock",
        "nombre": "Rock Sábado — Kafe Antzokia",
        "url": "https://www.kafeantzokia.eus/",
        "fecha": "2026-05-09",
        "hora": "22:00",
        "fecha_utc": "2026-05-09T20:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Alternative",
        "recinto_id": "rec-kafe-antzokia-may09",
        "recinto_nombre": "Kafe Antzokia",
        "ciudad": "Bilbao",
        "direccion": "Done Bikendi Kalea, 2, 48001 Bilbao",
        "latitud": 43.2626,
        "longitud": -2.9270,
        "artista_id": "art-kafe-rock",
        "artista_nombre": "Berri Txarrak",
        "artista_imagen": "https://picsum.photos/seed/kafe-rock/400/400",
        "imagen_evento": "https://picsum.photos/seed/kafe-rock-event/800/450",
        "promotor": "Kafe Bilbao",
    },
    # ── Today: May 10 ────────────────────────────────────────────────────────────
    {
        "id": "evt-may10-madrid-jazz",
        "nombre": "Jazz en el Retiro — Tarde de Domingo",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-05-10",
        "hora": "18:00",
        "fecha_utc": "2026-05-10T16:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-retiro",
        "recinto_nombre": "Parque del Retiro",
        "ciudad": "Madrid",
        "direccion": "Plaza de la Independencia, 7, 28001 Madrid",
        "latitud": 40.4153,
        "longitud": -3.6844,
        "artista_id": "art-retiro-jazz",
        "artista_nombre": "Trío Madrid Jazz",
        "artista_imagen": "https://picsum.photos/seed/retiro-jazz/400/400",
        "imagen_evento": "https://picsum.photos/seed/retiro-jazz-event/800/450",
        "promotor": "Madrid Jazz Festival",
    },
    {
        "id": "evt-may10-bcn-indie",
        "nombre": "Indie Sunday — Sala Apolo",
        "url": "https://www.sala-apolo.com/",
        "fecha": "2026-05-10",
        "hora": "21:00",
        "fecha_utc": "2026-05-10T19:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Indie",
        "recinto_id": "rec-apolo",
        "recinto_nombre": "Sala Apolo",
        "ciudad": "Barcelona",
        "direccion": "Carrer Nou de la Rambla, 113, 08004 Barcelona",
        "latitud": 41.3757,
        "longitud": 2.1647,
        "artista_id": "art-apolo-indie",
        "artista_nombre": "Los Modernos",
        "artista_imagen": "https://picsum.photos/seed/apolo-indie/400/400",
        "imagen_evento": "https://picsum.photos/seed/apolo-indie-event/800/450",
        "promotor": "Apolo Live",
    },
    {
        "id": "evt-may10-valencia-comedy",
        "nombre": "Domingo de Monólogos — Centro Cultural",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-05-10",
        "hora": "20:00",
        "fecha_utc": "2026-05-10T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Comedy",
        "subgenero": "Stand-up",
        "recinto_id": "rec-principal-val",
        "recinto_nombre": "Teatro Principal Valencia",
        "ciudad": "Valencia",
        "direccion": "Carrer de les Barques, 15, 46002 Valencia",
        "latitud": 39.4707,
        "longitud": -0.3747,
        "artista_id": "art-monologos-val",
        "artista_nombre": "Carlos Ferrer",
        "artista_imagen": "https://picsum.photos/seed/monologos-val/400/400",
        "imagen_evento": "https://picsum.photos/seed/monologos-val-event/800/450",
        "promotor": "Comedy Valencia",
    },
    # ── May 11 ────────────────────────────────────────────────────────────────────
    {
        "id": "evt-may11-madrid-electronic",
        "nombre": "Lunes Electrónico — Fabrik Madrid",
        "url": "https://www.fabricmadrid.es/",
        "fecha": "2026-05-11",
        "hora": "23:00",
        "fecha_utc": "2026-05-11T21:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Techno",
        "recinto_id": "rec-fabrik",
        "recinto_nombre": "Fabrik Madrid",
        "ciudad": "Madrid",
        "direccion": "Av. de la Industria, 82, 28938 Fuenlabrada",
        "latitud": 40.3189,
        "longitud": -3.8006,
        "artista_id": "art-fabrik-techno",
        "artista_nombre": "DJ Óscar Mulero",
        "artista_imagen": "https://picsum.photos/seed/fabrik-techno/400/400",
        "imagen_evento": "https://picsum.photos/seed/fabrik-techno-event/800/450",
        "promotor": "Fabrik",
    },
    {
        "id": "evt-may11-sevilla-flamenco",
        "nombre": "Noche Flamenca — Casa de la Memoria",
        "url": "https://www.casadelamemoria.es/",
        "fecha": "2026-05-11",
        "hora": "21:30",
        "fecha_utc": "2026-05-11T19:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-memoria",
        "recinto_nombre": "Casa de la Memoria",
        "ciudad": "Sevilla",
        "direccion": "Calle Cuna, 6, 41004 Sevilla",
        "latitud": 37.3908,
        "longitud": -5.9934,
        "artista_id": "art-memoria-flamenco",
        "artista_nombre": "Compañía Rocío Molina",
        "artista_imagen": "https://picsum.photos/seed/memoria-flamenco/400/400",
        "imagen_evento": "https://picsum.photos/seed/memoria-flamenco-event/800/450",
        "promotor": "Casa de la Memoria",
    },
    {
        "id": "evt-may11-bilbao-exhibition",
        "nombre": "Arte Contemporáneo — Azkuna Zentroa",
        "url": "https://www.azkunazentroa.eus/",
        "fecha": "2026-05-11",
        "hora": "18:30",
        "fecha_utc": "2026-05-11T16:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Exhibition",
        "subgenero": "Contemporary Art",
        "recinto_id": "rec-azkuna",
        "recinto_nombre": "Azkuna Zentroa",
        "ciudad": "Bilbao",
        "direccion": "Plaza Arriquibar, 4, 48010 Bilbao",
        "latitud": 43.2654,
        "longitud": -2.9342,
        "artista_id": "art-azkuna-art",
        "artista_nombre": "Colectivo Artea",
        "artista_imagen": "https://picsum.photos/seed/azkuna-art/400/400",
        "imagen_evento": "https://picsum.photos/seed/azkuna-art-event/800/450",
        "promotor": "Azkuna Zentroa",
    },
    # ── May 12 ────────────────────────────────────────────────────────────────────
    {
        "id": "evt-may12-madrid-pop",
        "nombre": "Pop en Vivo — Wizink Center",
        "url": "https://www.wizinkcenter.es/",
        "fecha": "2026-05-12",
        "hora": "21:00",
        "fecha_utc": "2026-05-12T19:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Pop",
        "subgenero": "Latin Pop",
        "recinto_id": "rec-wizink",
        "recinto_nombre": "WiZink Center",
        "ciudad": "Madrid",
        "direccion": "Av. de Felipe II, s/n, 28009 Madrid",
        "latitud": 40.4321,
        "longitud": -3.6634,
        "artista_id": "art-wizink-pop",
        "artista_nombre": "Rosalía",
        "artista_imagen": "https://picsum.photos/seed/wizink-pop/400/400",
        "imagen_evento": "https://picsum.photos/seed/wizink-pop-event/800/450",
        "promotor": "Live Nation ES",
    },
    {
        "id": "evt-may12-bcn-theatre",
        "nombre": "Teatro Grec — Obra de Estreno",
        "url": "https://www.barcelonafestival.com/",
        "fecha": "2026-05-12",
        "hora": "20:30",
        "fecha_utc": "2026-05-12T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Drama",
        "recinto_id": "rec-teatre-grec",
        "recinto_nombre": "Teatre Grec",
        "ciudad": "Barcelona",
        "direccion": "Passeig de Santa Madrona, 36, 08038 Barcelona",
        "latitud": 41.3701,
        "longitud": 2.1576,
        "artista_id": "art-grec-drama",
        "artista_nombre": "Companyia Grec",
        "artista_imagen": "https://picsum.photos/seed/grec-drama/400/400",
        "imagen_evento": "https://picsum.photos/seed/grec-drama-event/800/450",
        "promotor": "Institut de Cultura",
    },
    {
        "id": "evt-may12-malaga-sports",
        "nombre": "Fútbol Sala — Liga Nacional Málaga",
        "url": "https://www.malaga.eu/",
        "fecha": "2026-05-12",
        "hora": "19:00",
        "fecha_utc": "2026-05-12T17:00:00Z",
        "estado": "onsale",
        "segmento": "Sports",
        "genero": "Football",
        "subgenero": "Futsal",
        "recinto_id": "rec-martin-carpena",
        "recinto_nombre": "Palacio de los Deportes Martín Carpena",
        "ciudad": "Málaga",
        "direccion": "Av. de la Ilusión, s/n, 29004 Málaga",
        "latitud": 36.7083,
        "longitud": -4.4344,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": "https://picsum.photos/seed/futsal-malaga-event/800/450",
        "promotor": "Liga Nacional",
    },
    # ── May 13 ────────────────────────────────────────────────────────────────────
    {
        "id": "evt-may13-madrid-rock",
        "nombre": "Rock al Parque — Ensayo General",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-05-13",
        "hora": "20:00",
        "fecha_utc": "2026-05-13T18:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Alternative",
        "recinto_id": "rec-riviera-mad",
        "recinto_nombre": "La Riviera",
        "ciudad": "Madrid",
        "direccion": "Paseo Bajo de la Virgen del Puerto, s/n, 28005 Madrid",
        "latitud": 40.4108,
        "longitud": -3.7221,
        "artista_id": "art-rock-parque",
        "artista_nombre": "Vetusta Morla",
        "artista_imagen": "https://picsum.photos/seed/rock-parque/400/400",
        "imagen_evento": "https://picsum.photos/seed/rock-parque-event/800/450",
        "promotor": "Rock al Parque",
    },
    {
        "id": "evt-may13-zaragoza-family",
        "nombre": "Ciencia Divertida — Taller Infantil",
        "url": "https://www.caixaforum.org/",
        "fecha": "2026-05-13",
        "hora": "12:00",
        "fecha_utc": "2026-05-13T10:00:00Z",
        "estado": "onsale",
        "segmento": "Family",
        "genero": "Kids",
        "subgenero": "Science",
        "recinto_id": "rec-caixaforum-zgz",
        "recinto_nombre": "CaixaForum Zaragoza",
        "ciudad": "Zaragoza",
        "direccion": "Av. de José Anselmo Clavé, 4, 50004 Zaragoza",
        "latitud": 41.6483,
        "longitud": -0.8944,
        "artista_id": "art-ciencia-divertida",
        "artista_nombre": "Explora Lab",
        "artista_imagen": "https://picsum.photos/seed/ciencia-divertida/400/400",
        "imagen_evento": "https://picsum.photos/seed/ciencia-divertida-event/800/450",
        "promotor": "CaixaForum",
    },
    {
        "id": "evt-may13-granada-jazz",
        "nombre": "Granada Jazz Club — Miércoles en Vivo",
        "url": "https://www.granada.org/",
        "fecha": "2026-05-13",
        "hora": "22:00",
        "fecha_utc": "2026-05-13T20:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-el-camborio",
        "recinto_nombre": "El Camborio",
        "ciudad": "Granada",
        "direccion": "Camino del Sacromonte, 48, 18010 Granada",
        "latitud": 37.1798,
        "longitud": -3.5866,
        "artista_id": "art-granada-jazz",
        "artista_nombre": "Cuarteto del Sur",
        "artista_imagen": "https://picsum.photos/seed/granada-jazz/400/400",
        "imagen_evento": "https://picsum.photos/seed/granada-jazz-event/800/450",
        "promotor": "Granada Jazz",
    },
    # ── Expired event — verify "no expired events" fix ────────────────────────────
    {
        "id": "evt-expired-test",
        "nombre": "EXPIRED TEST — Should Not Appear on Map",
        "url": None,
        "fecha": "2026-01-01",
        "hora": "20:00",
        "fecha_utc": "2026-01-01T19:00:00Z",
        "estado": "offsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Test",
        "recinto_id": "rec-expired-test",
        "recinto_nombre": "Test Venue",
        "ciudad": "Madrid",
        "direccion": "Calle Test, 1, 28001 Madrid",
        "latitud": 40.4168,
        "longitud": -3.7038,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": None,
        "promotor": None,
    },
    {
        "id": "evt-madrid-neon-pulse",
        "nombre": "Neon Pulse — Synthwave Night",
        "url": "https://www.ticketmaster.es/search?q=La+Riviera",
        "fecha": "2026-05-14",
        "hora": "22:00",
        "fecha_utc": "2026-05-14T20:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Synthwave",
        "recinto_id": "rec-la-riviera",
        "recinto_nombre": "La Riviera",
        "ciudad": "Madrid",
        "direccion": "Paseo Bajo de la Virgen del Puerto, s/n, 28005 Madrid",
        "latitud": 40.4108,
        "longitud": -3.7221,
        "artista_id": "art-neon-pulse",
        "artista_nombre": "Neon Pulse Collective",
        "artista_imagen": "https://picsum.photos/seed/neon-pulse/400/400",
        "imagen_evento": "https://picsum.photos/seed/neon-pulse-event/800/450",
        "promotor": "Live Nation ES",
    },
    {
        "id": "evt-madrid-matadero-digital-soul",
        "nombre": "Digital Soul — Immersive Exhibition",
        "url": "https://www.mataderomadrid.org/",
        "fecha": "2026-05-18",
        "hora": "19:30",
        "fecha_utc": "2026-05-18T17:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Multimedia",
        "subgenero": "Digital Art",
        "recinto_id": "rec-matadero",
        "recinto_nombre": "Matadero Madrid",
        "ciudad": "Madrid",
        "direccion": "Plaza de Legazpi, 8, 28045 Madrid",
        "latitud": 40.3905,
        "longitud": -3.6975,
        "artista_id": "art-digital-soul",
        "artista_nombre": "Collective AV",
        "artista_imagen": "https://picsum.photos/seed/digital-soul/400/400",
        "imagen_evento": "https://picsum.photos/seed/digital-soul-event/800/450",
        "promotor": "Matadero",
    },
    {
        "id": "evt-bcn-sonar-warmup",
        "nombre": "Sónar Warm-up — Underground Techno",
        "url": "https://www.salarazzmatazz.com/",
        "fecha": "2026-06-12",
        "hora": "23:30",
        "fecha_utc": "2026-06-12T21:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Techno",
        "recinto_id": "rec-razzmatazz",
        "recinto_nombre": "Razzmatazz",
        "ciudad": "Barcelona",
        "direccion": "Carrer dels Almogàvers, 122, 08018 Barcelona",
        "latitud": 41.3980,
        "longitud": 2.1909,
        "artista_id": "art-sonar-warmup",
        "artista_nombre": "Hex Resident",
        "artista_imagen": "https://picsum.photos/seed/sonar-warmup/400/400",
        "imagen_evento": "https://picsum.photos/seed/sonar-warmup-event/800/450",
        "promotor": "Advanced Music",
    },
    {
        "id": "evt-valencia-cinema-under-stars",
        "nombre": "Cinema Under the Stars — Blade Runner 2049",
        "url": "https://www.filmin.es/pelicula/blade-runner-2049",
        "fecha": "2026-07-04",
        "hora": "22:00",
        "fecha_utc": "2026-07-04T20:00:00Z",
        "estado": "onsale",
        "segmento": "Film",
        "genero": "Sci-Fi",
        "subgenero": "Cyberpunk",
        "recinto_id": "rec-jardines-palau",
        "recinto_nombre": "Jardines del Palau",
        "ciudad": "Valencia",
        "direccion": "Passeig de l'Albereda, 30, 46023 Valencia",
        "latitud": 39.4578,
        "longitud": -0.3540,
        "artista_id": None,
        "artista_nombre": "Ridley Scott (dir.)",
        "artista_imagen": "https://picsum.photos/seed/blade-runner/400/400",
        "imagen_evento": "https://picsum.photos/seed/cinema-stars-event/800/450",
        "promotor": "Cinema al Fresco",
    },
    {
        "id": "evt-madrid-wanda-derbi",
        "nombre": "Derbi Madrileño — Atleti vs Real Madrid",
        "url": "https://www.atleticodemadrid.com/entradas",
        "fecha": "2026-05-24",
        "hora": "21:00",
        "fecha_utc": "2026-05-24T19:00:00Z",
        "estado": "onsale",
        "segmento": "Sports",
        "genero": "Soccer",
        "subgenero": "La Liga",
        "recinto_id": "rec-metropolitano",
        "recinto_nombre": "Riyadh Air Metropolitano",
        "ciudad": "Madrid",
        "direccion": "Av. de Luis Aragonés, 4, 28022 Madrid",
        "latitud": 40.4362,
        "longitud": -3.5996,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": "https://picsum.photos/seed/derbi-event/800/450",
        "promotor": "La Liga",
    },
    {
        "id": "evt-madrid-neon-pulse-night2",
        "nombre": "Neon Pulse — Synthwave Night",
        "url": "https://www.ticketmaster.es/search?q=La+Riviera",
        "fecha": "2026-05-15",
        "hora": "22:00",
        "fecha_utc": "2026-05-15T20:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Synthwave",
        "recinto_id": "rec-la-riviera",
        "recinto_nombre": "La Riviera",
        "ciudad": "Madrid",
        "direccion": "Paseo Bajo de la Virgen del Puerto, s/n, 28005 Madrid",
        "latitud": 40.4108,
        "longitud": -3.7221,
        "artista_id": "art-neon-pulse",
        "artista_nombre": "Neon Pulse Collective",
        "artista_imagen": "https://picsum.photos/seed/neon-pulse/400/400",
        "imagen_evento": "https://picsum.photos/seed/neon-pulse-event/800/450",
        "promotor": "Live Nation ES",
    },
    {
        "id": "evt-madrid-neon-pulse-night2-late",
        "nombre": "Neon Pulse — Synthwave Night",
        "url": "https://www.ticketmaster.es/search?q=La+Riviera",
        "fecha": "2026-05-15",
        "hora": "01:30",
        "fecha_utc": "2026-05-15T23:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Synthwave",
        "recinto_id": "rec-la-riviera",
        "recinto_nombre": "La Riviera",
        "ciudad": "Madrid",
        "direccion": "Paseo Bajo de la Virgen del Puerto, s/n, 28005 Madrid",
        "latitud": 40.4108,
        "longitud": -3.7221,
        "artista_id": "art-neon-pulse",
        "artista_nombre": "Neon Pulse Collective",
        "artista_imagen": "https://picsum.photos/seed/neon-pulse/400/400",
        "imagen_evento": "https://picsum.photos/seed/neon-pulse-event/800/450",
        "promotor": "Live Nation ES",
    },
    {
        "id": "evt-madrid-neon-pulse-night3",
        "nombre": "Neon Pulse — Synthwave Night",
        "url": "https://www.ticketmaster.es/search?q=La+Riviera",
        "fecha": "2026-05-16",
        "hora": "22:00",
        "fecha_utc": "2026-05-16T20:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Synthwave",
        "recinto_id": "rec-la-riviera",
        "recinto_nombre": "La Riviera",
        "ciudad": "Madrid",
        "direccion": "Paseo Bajo de la Virgen del Puerto, s/n, 28005 Madrid",
        "latitud": 40.4108,
        "longitud": -3.7221,
        "artista_id": "art-neon-pulse",
        "artista_nombre": "Neon Pulse Collective",
        "artista_imagen": "https://picsum.photos/seed/neon-pulse/400/400",
        "imagen_evento": "https://picsum.photos/seed/neon-pulse-event/800/450",
        "promotor": "Live Nation ES",
    },
    {
        "id": "evt-bcn-sonar-warmup-night2",
        "nombre": "Sónar Warm-up — Underground Techno",
        "url": "https://www.salarazzmatazz.com/",
        "fecha": "2026-06-13",
        "hora": "23:30",
        "fecha_utc": "2026-06-13T21:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Techno",
        "recinto_id": "rec-razzmatazz",
        "recinto_nombre": "Razzmatazz",
        "ciudad": "Barcelona",
        "direccion": "Carrer dels Almogàvers, 122, 08018 Barcelona",
        "latitud": 41.3980,
        "longitud": 2.1909,
        "artista_id": "art-sonar-warmup",
        "artista_nombre": "Hex Resident",
        "artista_imagen": "https://picsum.photos/seed/sonar-warmup/400/400",
        "imagen_evento": "https://picsum.photos/seed/sonar-warmup-event/800/450",
        "promotor": "Advanced Music",
    },
    {
        "id": "evt-sevilla-flamenco-clandestino",
        "nombre": "Flamenco Clandestino — Tablao Íntimo",
        "url": "https://www.tablaolosgallos.com/",
        "fecha": "2026-05-30",
        "hora": "23:00",
        "fecha_utc": "2026-05-30T21:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Flamenco",
        "subgenero": "Traditional",
        "recinto_id": "rec-casa-carmen",
        "recinto_nombre": "Casa de Carmen",
        "ciudad": "Sevilla",
        "direccion": "Calle Marqués de Paradas, 30, 41001 Sevilla",
        "latitud": 37.3891,
        "longitud": -5.9845,
        "artista_id": "art-carmen",
        "artista_nombre": "Carmen del Río",
        "artista_imagen": "https://picsum.photos/seed/carmen/400/400",
        "imagen_evento": "https://picsum.photos/seed/flamenco-event/800/450",
        "promotor": "Tablao Íntimo",
    },
    {
        "id": "evt-madrid-indie-rooftop",
        "nombre": "Azotea Indie — Sunset Session",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-05-21",
        "hora": "20:30",
        "fecha_utc": "2026-05-21T18:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Indie",
        "recinto_id": "rec-circulo-bellas-artes",
        "recinto_nombre": "Círculo de Bellas Artes",
        "ciudad": "Madrid",
        "direccion": "Calle de Alcalá, 42, 28014 Madrid",
        "latitud": 40.4186,
        "longitud": -3.6965,
        "artista_id": "art-azotea-indie",
        "artista_nombre": "Los Satélites",
        "artista_imagen": "https://picsum.photos/seed/azotea-indie/400/400",
        "imagen_evento": "https://picsum.photos/seed/azotea-indie-event/800/450",
        "promotor": "Madrid Live",
    },
    {
        "id": "evt-madrid-comedy-late",
        "nombre": "Malasaña Stand-up — Late Show",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-05-22",
        "hora": "21:30",
        "fecha_utc": "2026-05-22T19:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Comedy",
        "subgenero": "Stand-up",
        "recinto_id": "rec-teatro-maravillas",
        "recinto_nombre": "Teatro Maravillas",
        "ciudad": "Madrid",
        "direccion": "Calle de Manuela Malasaña, 6, 28004 Madrid",
        "latitud": 40.4277,
        "longitud": -3.7033,
        "artista_id": "art-comedy-late",
        "artista_nombre": "Paula Navas",
        "artista_imagen": "https://picsum.photos/seed/comedy-late/400/400",
        "imagen_evento": "https://picsum.photos/seed/comedy-late-event/800/450",
        "promotor": "Comedy Club Madrid",
    },
    {
        "id": "evt-madrid-jazz-chamber",
        "nombre": "Chamber Jazz — Noches del Conde Duque",
        "url": "https://www.condeduquemadrid.es/",
        "fecha": "2026-06-03",
        "hora": "20:00",
        "fecha_utc": "2026-06-03T18:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Jazz",
        "recinto_id": "rec-conde-duque",
        "recinto_nombre": "Centro Conde Duque",
        "ciudad": "Madrid",
        "direccion": "Calle del Conde Duque, 11, 28015 Madrid",
        "latitud": 40.4283,
        "longitud": -3.7101,
        "artista_id": "art-chamber-jazz",
        "artista_nombre": "Nerea Quartet",
        "artista_imagen": "https://picsum.photos/seed/chamber-jazz/400/400",
        "imagen_evento": "https://picsum.photos/seed/chamber-jazz-event/800/450",
        "promotor": "Conde Duque",
    },
    {
        "id": "evt-madrid-family-circus",
        "nombre": "Circo Miniatura — Acrobacias en Familia",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-06-07",
        "hora": "12:00",
        "fecha_utc": "2026-06-07T10:00:00Z",
        "estado": "onsale",
        "segmento": "Family",
        "genero": "Kids",
        "subgenero": "Circus",
        "recinto_id": "rec-teatro-circo-price",
        "recinto_nombre": "Teatro Circo Price",
        "ciudad": "Madrid",
        "direccion": "Ronda de Atocha, 35, 28012 Madrid",
        "latitud": 40.4057,
        "longitud": -3.6964,
        "artista_id": "art-circo-miniatura",
        "artista_nombre": "Compañía Voltereta",
        "artista_imagen": "https://picsum.photos/seed/circo-miniatura/400/400",
        "imagen_evento": "https://picsum.photos/seed/circo-miniatura-event/800/450",
        "promotor": "Price Kids",
    },
    {
        "id": "evt-barcelona-pop-palau",
        "nombre": "Pop Mediterrani — Nit al Palau",
        "url": "https://www.palaumusica.cat/",
        "fecha": "2026-06-18",
        "hora": "21:00",
        "fecha_utc": "2026-06-18T19:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Pop",
        "subgenero": "Mediterranean Pop",
        "recinto_id": "rec-palau-musica",
        "recinto_nombre": "Palau de la Música Catalana",
        "ciudad": "Barcelona",
        "direccion": "Carrer Palau de la Música, 4-6, 08003 Barcelona",
        "latitud": 41.3876,
        "longitud": 2.1753,
        "artista_id": "art-pop-mediterrani",
        "artista_nombre": "Mar Blava",
        "artista_imagen": "https://picsum.photos/seed/pop-mediterrani/400/400",
        "imagen_evento": "https://picsum.photos/seed/pop-mediterrani-event/800/450",
        "promotor": "Palau Live",
    },
    {
        "id": "evt-barcelona-basket-playoffs",
        "nombre": "Basket Playoffs — Barcelona vs Valencia",
        "url": "https://www.fcbarcelona.com/",
        "fecha": "2026-06-20",
        "hora": "19:00",
        "fecha_utc": "2026-06-20T17:00:00Z",
        "estado": "onsale",
        "segmento": "Sports",
        "genero": "Basketball",
        "subgenero": "ACB",
        "recinto_id": "rec-palau-blaugrana",
        "recinto_nombre": "Palau Blaugrana",
        "ciudad": "Barcelona",
        "direccion": "Av. de Joan XXIII, s/n, 08028 Barcelona",
        "latitud": 41.3809,
        "longitud": 2.1202,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": "https://picsum.photos/seed/basket-playoffs-event/800/450",
        "promotor": "ACB",
    },
    {
        "id": "evt-barcelona-design-lab",
        "nombre": "Design Lab — Futuros Domésticos",
        "url": "https://ajuntament.barcelona.cat/dissenyhub/",
        "fecha": "2026-06-25",
        "hora": "18:00",
        "fecha_utc": "2026-06-25T16:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Exhibition",
        "subgenero": "Design",
        "recinto_id": "rec-disseny-hub",
        "recinto_nombre": "Disseny Hub Barcelona",
        "ciudad": "Barcelona",
        "direccion": "Plaça de les Glòries Catalanes, 37, 08018 Barcelona",
        "latitud": 41.4033,
        "longitud": 2.1877,
        "artista_id": "art-design-lab",
        "artista_nombre": "Studio Habitat",
        "artista_imagen": "https://picsum.photos/seed/design-lab/400/400",
        "imagen_evento": "https://picsum.photos/seed/design-lab-event/800/450",
        "promotor": "Disseny Hub",
    },
    {
        "id": "evt-valencia-electronic-marina",
        "nombre": "Marina Beats — Electronic Open Air",
        "url": "https://www.lamarinadevalencia.com/",
        "fecha": "2026-07-10",
        "hora": "22:30",
        "fecha_utc": "2026-07-10T20:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "House",
        "recinto_id": "rec-marina-valencia",
        "recinto_nombre": "La Marina de Valencia",
        "ciudad": "Valencia",
        "direccion": "Carrer del Moll de la Duana, s/n, 46024 Valencia",
        "latitud": 39.4621,
        "longitud": -0.3246,
        "artista_id": "art-marina-beats",
        "artista_nombre": "Costa Norte DJs",
        "artista_imagen": "https://picsum.photos/seed/marina-beats/400/400",
        "imagen_evento": "https://picsum.photos/seed/marina-beats-event/800/450",
        "promotor": "Marina Music",
    },
    {
        "id": "evt-valencia-theatre-noir",
        "nombre": "Noir al Principal — Thriller Escénico",
        "url": "https://teatreprincipalvalencia.com/",
        "fecha": "2026-07-12",
        "hora": "20:30",
        "fecha_utc": "2026-07-12T18:30:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Thriller",
        "recinto_id": "rec-teatre-principal",
        "recinto_nombre": "Teatre Principal de València",
        "ciudad": "Valencia",
        "direccion": "Carrer de les Barques, 15, 46002 Valencia",
        "latitud": 39.4707,
        "longitud": -0.3747,
        "artista_id": "art-noir-principal",
        "artista_nombre": "La Companyia Fosca",
        "artista_imagen": "https://picsum.photos/seed/noir-principal/400/400",
        "imagen_evento": "https://picsum.photos/seed/noir-principal-event/800/450",
        "promotor": "Teatre Principal",
    },
    {
        "id": "evt-valencia-tennis-finals",
        "nombre": "Valencia Tennis Finals — Sesión Tarde",
        "url": "https://www.valenciaopen.com/",
        "fecha": "2026-07-18",
        "hora": "18:00",
        "fecha_utc": "2026-07-18T16:00:00Z",
        "estado": "onsale",
        "segmento": "Sports",
        "genero": "Tennis",
        "subgenero": "Finals",
        "recinto_id": "rec-fonteta",
        "recinto_nombre": "Pavelló Font de Sant Lluís",
        "ciudad": "Valencia",
        "direccion": "Av. dels Germans Maristes, 16, 46013 Valencia",
        "latitud": 39.4563,
        "longitud": -0.3634,
        "artista_id": None,
        "artista_nombre": None,
        "artista_imagen": None,
        "imagen_evento": "https://picsum.photos/seed/tennis-finals-event/800/450",
        "promotor": "Valencia Open",
    },
    {
        "id": "evt-sevilla-guitar-nights",
        "nombre": "Guitar Nights — Patios de Sevilla",
        "url": "https://www.sevilla.org/",
        "fecha": "2026-06-05",
        "hora": "21:30",
        "fecha_utc": "2026-06-05T19:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Spanish Guitar",
        "recinto_id": "rec-patio-banderas",
        "recinto_nombre": "Patio de Banderas",
        "ciudad": "Sevilla",
        "direccion": "Patio de Banderas, 41004 Sevilla",
        "latitud": 37.3845,
        "longitud": -5.9911,
        "artista_id": "art-guitar-nights",
        "artista_nombre": "Álvaro Mesa",
        "artista_imagen": "https://picsum.photos/seed/guitar-nights/400/400",
        "imagen_evento": "https://picsum.photos/seed/guitar-nights-event/800/450",
        "promotor": "Noches de Patio",
    },
    {
        "id": "evt-sevilla-family-magic",
        "nombre": "Magia de Cerca — Domingo Familiar",
        "url": "https://www.teatrolamaestranza.es/",
        "fecha": "2026-06-14",
        "hora": "11:30",
        "fecha_utc": "2026-06-14T09:30:00Z",
        "estado": "onsale",
        "segmento": "Family",
        "genero": "Kids",
        "subgenero": "Magic",
        "recinto_id": "rec-maestranza",
        "recinto_nombre": "Teatro de la Maestranza",
        "ciudad": "Sevilla",
        "direccion": "Paseo de Cristóbal Colón, 22, 41001 Sevilla",
        "latitud": 37.3861,
        "longitud": -5.9983,
        "artista_id": "art-magia-cerca",
        "artista_nombre": "Lola Linterna",
        "artista_imagen": "https://picsum.photos/seed/magia-cerca/400/400",
        "imagen_evento": "https://picsum.photos/seed/magia-cerca-event/800/450",
        "promotor": "Maestranza Familiar",
    },
    {
        "id": "evt-bilbao-rock-ria",
        "nombre": "Rock en la Ría — Noche Alternativa",
        "url": "https://www.bilbao.eus/",
        "fecha": "2026-06-19",
        "hora": "22:00",
        "fecha_utc": "2026-06-19T20:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Rock",
        "subgenero": "Alternative",
        "recinto_id": "rec-kafe-antzokia",
        "recinto_nombre": "Kafe Antzokia",
        "ciudad": "Bilbao",
        "direccion": "Done Bikendi Kalea, 2, 48001 Bilbao",
        "latitud": 43.2626,
        "longitud": -2.9270,
        "artista_id": "art-rock-ria",
        "artista_nombre": "Marea Norte",
        "artista_imagen": "https://picsum.photos/seed/rock-ria/400/400",
        "imagen_evento": "https://picsum.photos/seed/rock-ria-event/800/450",
        "promotor": "Bilbao Gaua",
    },
    {
        "id": "evt-bilbao-guggenheim-afterdark",
        "nombre": "Guggenheim Afterdark — Arte y Electrónica",
        "url": "https://www.guggenheim-bilbao.eus/",
        "fecha": "2026-06-26",
        "hora": "21:00",
        "fecha_utc": "2026-06-26T19:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Exhibition",
        "subgenero": "Contemporary Art",
        "recinto_id": "rec-guggenheim-bilbao",
        "recinto_nombre": "Museo Guggenheim Bilbao",
        "ciudad": "Bilbao",
        "direccion": "Abandoibarra Etorb., 2, 48009 Bilbao",
        "latitud": 43.2687,
        "longitud": -2.9340,
        "artista_id": "art-afterdark",
        "artista_nombre": "Lumen Studio",
        "artista_imagen": "https://picsum.photos/seed/guggenheim-afterdark/400/400",
        "imagen_evento": "https://picsum.photos/seed/guggenheim-afterdark-event/800/450",
        "promotor": "Guggenheim Bilbao",
    },
    {
        "id": "evt-malaga-urban-night",
        "nombre": "Urban Night — Puerto de Málaga",
        "url": "https://www.malaga.eu/",
        "fecha": "2026-07-03",
        "hora": "23:00",
        "fecha_utc": "2026-07-03T21:00:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Urban",
        "subgenero": "Hip Hop",
        "recinto_id": "rec-muelle-uno",
        "recinto_nombre": "Muelle Uno",
        "ciudad": "Málaga",
        "direccion": "Paseo del Muelle Uno, 4, 29016 Málaga",
        "latitud": 36.7188,
        "longitud": -4.4151,
        "artista_id": "art-urban-night",
        "artista_nombre": "Sur Crew",
        "artista_imagen": "https://picsum.photos/seed/urban-night/400/400",
        "imagen_evento": "https://picsum.photos/seed/urban-night-event/800/450",
        "promotor": "Málaga Urbana",
    },
    {
        "id": "evt-malaga-comedy-beach",
        "nombre": "Comedy Beach — Monólogos al Aire Libre",
        "url": "https://www.malaga.eu/",
        "fecha": "2026-07-08",
        "hora": "21:00",
        "fecha_utc": "2026-07-08T19:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Comedy",
        "subgenero": "Monologues",
        "recinto_id": "rec-teatro-soho",
        "recinto_nombre": "Teatro del Soho CaixaBank",
        "ciudad": "Málaga",
        "direccion": "Calle Córdoba, 13, 29001 Málaga",
        "latitud": 36.7187,
        "longitud": -4.4247,
        "artista_id": "art-comedy-beach",
        "artista_nombre": "Dani Costa",
        "artista_imagen": "https://picsum.photos/seed/comedy-beach/400/400",
        "imagen_evento": "https://picsum.photos/seed/comedy-beach-event/800/450",
        "promotor": "Soho Comedy",
    },
    {
        "id": "evt-zaragoza-electro-ebro",
        "nombre": "Electro Ebro — Warehouse Session",
        "url": "https://www.zaragoza.es/",
        "fecha": "2026-06-27",
        "hora": "23:45",
        "fecha_utc": "2026-06-27T21:45:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Electronic",
        "subgenero": "Warehouse",
        "recinto_id": "rec-las-armas",
        "recinto_nombre": "Centro Musical Las Armas",
        "ciudad": "Zaragoza",
        "direccion": "Plaza Mariano de Cavia, 2, 50003 Zaragoza",
        "latitud": 41.6550,
        "longitud": -0.8852,
        "artista_id": "art-electro-ebro",
        "artista_nombre": "Ebro System",
        "artista_imagen": "https://picsum.photos/seed/electro-ebro/400/400",
        "imagen_evento": "https://picsum.photos/seed/electro-ebro-event/800/450",
        "promotor": "Las Armas",
    },
    {
        "id": "evt-zaragoza-family-science",
        "nombre": "Ciencia en Vivo — Taller Familiar",
        "url": "https://www.caixaforum.org/",
        "fecha": "2026-07-05",
        "hora": "11:00",
        "fecha_utc": "2026-07-05T09:00:00Z",
        "estado": "onsale",
        "segmento": "Family",
        "genero": "Exhibition",
        "subgenero": "Science",
        "recinto_id": "rec-caixaforum-zaragoza",
        "recinto_nombre": "CaixaForum Zaragoza",
        "ciudad": "Zaragoza",
        "direccion": "Av. de José Anselmo Clavé, 4, 50004 Zaragoza",
        "latitud": 41.6483,
        "longitud": -0.8944,
        "artista_id": "art-ciencia-vivo",
        "artista_nombre": "Explora Lab",
        "artista_imagen": "https://picsum.photos/seed/ciencia-vivo/400/400",
        "imagen_evento": "https://picsum.photos/seed/ciencia-vivo-event/800/450",
        "promotor": "CaixaForum",
    },
    {
        "id": "evt-granada-flamenco-cueva",
        "nombre": "Flamenco en Cueva — Sacromonte Vivo",
        "url": "https://www.granada.org/",
        "fecha": "2026-06-21",
        "hora": "22:00",
        "fecha_utc": "2026-06-21T20:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Theatre",
        "subgenero": "Flamenco",
        "recinto_id": "rec-sacromonte",
        "recinto_nombre": "Cuevas del Sacromonte",
        "ciudad": "Granada",
        "direccion": "Camino del Sacromonte, 89, 18010 Granada",
        "latitud": 37.1809,
        "longitud": -3.5881,
        "artista_id": "art-sacromonte-vivo",
        "artista_nombre": "Elena Carmona",
        "artista_imagen": "https://picsum.photos/seed/sacromonte-vivo/400/400",
        "imagen_evento": "https://picsum.photos/seed/sacromonte-vivo-event/800/450",
        "promotor": "Sacromonte Vivo",
    },
    {
        "id": "evt-granada-classical-alhambra",
        "nombre": "Noches de Cámara — Jardines de la Alhambra",
        "url": "https://www.alhambra-patronato.es/",
        "fecha": "2026-07-11",
        "hora": "21:30",
        "fecha_utc": "2026-07-11T19:30:00Z",
        "estado": "onsale",
        "segmento": "Music",
        "genero": "Classical",
        "subgenero": "Chamber Music",
        "recinto_id": "rec-alhambra-jardines",
        "recinto_nombre": "Jardines de la Alhambra",
        "ciudad": "Granada",
        "direccion": "Calle Real de la Alhambra, s/n, 18009 Granada",
        "latitud": 37.1761,
        "longitud": -3.5881,
        "artista_id": "art-alhambra-camara",
        "artista_nombre": "Trío Nazarí",
        "artista_imagen": "https://picsum.photos/seed/alhambra-camara/400/400",
        "imagen_evento": "https://picsum.photos/seed/alhambra-camara-event/800/450",
        "promotor": "Festival Granada",
    },
    {
        "id": "evt-madrid-musical-granvia",
        "nombre": "Gran Vía Musical — Nueva Temporada",
        "url": "https://www.ticketmaster.es/",
        "fecha": "2026-06-11",
        "hora": "20:00",
        "fecha_utc": "2026-06-11T18:00:00Z",
        "estado": "onsale",
        "segmento": "Arts & Theatre",
        "genero": "Musical",
        "subgenero": "Musical",
        "recinto_id": "rec-teatro-lope-vega",
        "recinto_nombre": "Teatro Lope de Vega",
        "ciudad": "Madrid",
        "direccion": "Gran Vía, 57, 28013 Madrid",
        "latitud": 40.4227,
        "longitud": -3.7098,
        "artista_id": "art-granvia-musical",
        "artista_nombre": "Compañía Gran Vía",
        "artista_imagen": "https://picsum.photos/seed/granvia-musical/400/400",
        "imagen_evento": "https://picsum.photos/seed/granvia-musical-event/800/450",
        "promotor": "Stage Madrid",
    },
    {
        "id": "evt-barcelona-kids-aquarium",
        "nombre": "Exploradores del Mar — Aventura Infantil",
        "url": "https://www.aquariumbcn.com/",
        "fecha": "2026-07-02",
        "hora": "10:30",
        "fecha_utc": "2026-07-02T08:30:00Z",
        "estado": "onsale",
        "segmento": "Family",
        "genero": "Kids",
        "subgenero": "Aquarium",
        "recinto_id": "rec-aquarium-bcn",
        "recinto_nombre": "Aquàrium Barcelona",
        "ciudad": "Barcelona",
        "direccion": "Moll d'Espanya del Port Vell, s/n, 08039 Barcelona",
        "latitud": 41.3769,
        "longitud": 2.1841,
        "artista_id": "art-exploradores-mar",
        "artista_nombre": "Equipo Educativo Aquàrium",
        "artista_imagen": "https://picsum.photos/seed/exploradores-mar/400/400",
        "imagen_evento": "https://picsum.photos/seed/exploradores-mar-event/800/450",
        "promotor": "Aquàrium Barcelona",
    },
]


CITY_META = {
    "Madrid": {
        "latitud": 40.4168,
        "longitud": -3.7038,
        "direccion": "Centro de Madrid",
    },
    "Barcelona": {
        "latitud": 41.3874,
        "longitud": 2.1686,
        "direccion": "Centre de Barcelona",
    },
    "Valencia": {
        "latitud": 39.4699,
        "longitud": -0.3763,
        "direccion": "Centre de Valencia",
    },
    "Sevilla": {
        "latitud": 37.3891,
        "longitud": -5.9845,
        "direccion": "Centro de Sevilla",
    },
    "Bilbao": {
        "latitud": 43.2630,
        "longitud": -2.9350,
        "direccion": "Bilbao centro",
    },
    "Málaga": {
        "latitud": 36.7213,
        "longitud": -4.4214,
        "direccion": "Centro de Malaga",
    },
    "Zaragoza": {
        "latitud": 41.6488,
        "longitud": -0.8891,
        "direccion": "Centro de Zaragoza",
    },
    "Granada": {
        "latitud": 37.1773,
        "longitud": -3.5986,
        "direccion": "Centro de Granada",
    },
    "Alicante": {
        "latitud": 38.3452,
        "longitud": -0.4810,
        "direccion": "Centro de Alicante",
    },
    "A Coruña": {
        "latitud": 43.3623,
        "longitud": -8.4115,
        "direccion": "Centro de A Coruna",
    },
}


def _fixture_event(
    event_id: str,
    nombre: str,
    segmento: str,
    genero: str,
    subgenero: str,
    ciudad: str,
    fecha: str,
    hora: str,
    recinto_id: str,
    recinto_nombre: str,
) -> dict:
    city = CITY_META[ciudad]
    return {
        "id": event_id,
        "nombre": nombre,
        "url": "https://www.ticketmaster.es/",
        "fecha": fecha,
        "hora": hora,
        "fecha_utc": f"{fecha}T{hora}:00Z",
        "estado": "onsale",
        "segmento": segmento,
        "genero": genero,
        "subgenero": subgenero,
        "recinto_id": recinto_id,
        "recinto_nombre": recinto_nombre,
        "ciudad": ciudad,
        "direccion": city["direccion"],
        "latitud": city["latitud"],
        "longitud": city["longitud"],
        "artista_id": f"art-{event_id.removeprefix('evt-')}",
        "artista_nombre": nombre.split(" — ")[0],
        "artista_imagen": f"https://picsum.photos/seed/{event_id}-artist/400/400",
        "imagen_evento": f"https://picsum.photos/seed/{event_id}/800/450",
        "promotor": "Local Demo",
    }


EVENTS.extend(
    [
        # Music: 10
        _fixture_event("evt-demo-music-01", "Madrid Rock Club — Nuevas Guitarras", "Music", "Rock", "Indie Rock", "Madrid", "2026-07-15", "21:00", "rec-demo-music-mad-01", "Sala Mon Live"),
        _fixture_event("evt-demo-film-bcn-pop-lab", "Barcelona Film Lab — Verano Azul", "Film", "Drama", "Summer Cinema", "Barcelona", "2026-07-16", "20:30", "rec-demo-film-bcn-pop-lab", "Cines Verdi"),
        _fixture_event("evt-demo-film-val-bass-tide", "Valencia Dock Cinema — Marea Nocturna", "Film", "Sci-Fi", "Open Air Cinema", "Valencia", "2026-07-17", "23:30", "rec-demo-film-val-bass-tide", "La Filmoteca Valencia"),
        _fixture_event("evt-demo-film-sev-urban-flow", "Sevilla Urban Cinema — Historias del Sur", "Film", "Documentary", "Urban Culture", "Sevilla", "2026-07-18", "22:30", "rec-demo-film-sev-urban-flow", "Avenida 5 Cines"),
        _fixture_event("evt-demo-sports-bio-chamber", "Bilbao Basket Evening — Cuerdas y Canastas", "Sports", "Basketball", "Friendly", "Bilbao", "2026-07-19", "19:30", "rec-demo-sports-bio-chamber", "Bilbao Arena"),
        _fixture_event("evt-demo-sports-mal-sunset", "Malaga Sunset Football — Costa Cup", "Sports", "Football", "Summer Cup", "Málaga", "2026-07-20", "21:30", "rec-demo-sports-mal-sunset", "Estadio La Rosaleda"),
        _fixture_event("evt-demo-sports-zgz-electro", "Zaragoza Tennis Dome — Afterwork Match", "Sports", "Tennis", "Exhibition", "Zaragoza", "2026-07-21", "23:45", "rec-demo-sports-zgz-electro", "Stadium Casablanca"),
        _fixture_event("evt-demo-family-gra-guitar", "Granada Family Garden — Guitarras para Peques", "Family", "Kids", "Music Workshop", "Granada", "2026-07-22", "21:00", "rec-demo-family-gra-guitar", "Jardines del Generalife"),
        _fixture_event("evt-demo-family-ali-indie", "Alicante Family Pier — Juegos de Verano", "Family", "Kids", "Outdoor", "Alicante", "2026-07-23", "22:00", "rec-demo-family-ali-indie", "Muelle 12"),
        _fixture_event("evt-demo-family-cor-atlantic", "A Coruna Family Beats — Taller Atlantico", "Family", "Kids", "Creative Workshop", "A Coruña", "2026-07-24", "22:30", "rec-demo-family-cor-atlantic", "Domus"),
        # Sports: 10
        _fixture_event("evt-demo-sports-01", "Madrid Football Night — Capital Derby", "Sports", "Football", "La Liga", "Madrid", "2026-07-25", "21:00", "rec-demo-sports-mad-01", "Estadio Vallecas"),
        _fixture_event("evt-demo-sports-02", "Barcelona Basket Summer — Partido Estrella", "Sports", "Basketball", "ACB", "Barcelona", "2026-07-26", "19:00", "rec-demo-sports-bcn-01", "Palau Blaugrana"),
        _fixture_event("evt-demo-sports-03", "Valencia Tennis Open — Cuartos", "Sports", "Tennis", "Open", "Valencia", "2026-07-27", "18:00", "rec-demo-sports-val-01", "Club de Tenis Valencia"),
        _fixture_event("evt-demo-sports-04", "Sevilla Football Cup — Final Local", "Sports", "Football", "Cup", "Sevilla", "2026-07-28", "20:45", "rec-demo-sports-sev-01", "Estadio La Cartuja"),
        _fixture_event("evt-demo-sports-05", "Bilbao Basket Clash — Norte vs Sur", "Sports", "Basketball", "Friendly", "Bilbao", "2026-07-29", "19:30", "rec-demo-sports-bio-01", "Bilbao Arena"),
        _fixture_event("evt-demo-sports-06", "Malaga Beach Tennis — Session Sunset", "Sports", "Tennis", "Beach Tennis", "Málaga", "2026-07-30", "18:30", "rec-demo-sports-mal-01", "Playa de la Malagueta"),
        _fixture_event("evt-demo-sports-07", "Zaragoza Basket Weekend — Semifinal", "Sports", "Basketball", "Tournament", "Zaragoza", "2026-07-31", "20:00", "rec-demo-sports-zgz-01", "Pabellon Principe Felipe"),
        _fixture_event("evt-demo-sports-08", "Granada Football Summer — Amistoso", "Sports", "Football", "Friendly", "Granada", "2026-08-01", "21:15", "rec-demo-sports-gra-01", "Nuevo Los Carmenes"),
        _fixture_event("evt-demo-sports-09", "Alicante Tennis Night — Dobles Mixtos", "Sports", "Tennis", "Doubles", "Alicante", "2026-08-02", "19:00", "rec-demo-sports-ali-01", "Club Atletico Montemar"),
        _fixture_event("evt-demo-sports-10", "A Coruna Football Fest — Riazor Live", "Sports", "Football", "Friendly", "A Coruña", "2026-08-03", "20:30", "rec-demo-sports-cor-01", "Estadio Abanca-Riazor"),
        # Arts & Theatre: 10
        _fixture_event("evt-demo-arts-01", "Madrid Theatre Noir — Habitacion 17", "Arts & Theatre", "Theatre", "Drama", "Madrid", "2026-08-04", "20:30", "rec-demo-arts-mad-01", "Teatro Español"),
        _fixture_event("evt-demo-arts-02", "Barcelona Comedy Grid — Risas en Gracia", "Arts & Theatre", "Comedy", "Stand-up", "Barcelona", "2026-08-05", "21:30", "rec-demo-arts-bcn-01", "Teatreneu"),
        _fixture_event("evt-demo-arts-03", "Valencia Musical Port — Voces del Mar", "Arts & Theatre", "Musical", "Musical", "Valencia", "2026-08-06", "20:00", "rec-demo-arts-val-01", "Teatro Olympia"),
        _fixture_event("evt-demo-arts-04", "Sevilla Exhibition Light — Patio Abierto", "Arts & Theatre", "Exhibition", "Contemporary Art", "Sevilla", "2026-08-07", "18:30", "rec-demo-arts-sev-01", "CAAC Sevilla"),
        _fixture_event("evt-demo-arts-05", "Bilbao Theatre Lab — Escena Expandida", "Arts & Theatre", "Theatre", "Experimental", "Bilbao", "2026-08-08", "20:30", "rec-demo-arts-bio-01", "Pabellon 6"),
        _fixture_event("evt-demo-arts-06", "Malaga Comedy Club — Costa de Risas", "Arts & Theatre", "Comedy", "Monologues", "Málaga", "2026-08-09", "21:00", "rec-demo-arts-mal-01", "Teatro Echegaray"),
        _fixture_event("evt-demo-arts-07", "Zaragoza Musical Kids — La Ciudad Sonora", "Arts & Theatre", "Musical", "Family Musical", "Zaragoza", "2026-08-10", "18:00", "rec-demo-arts-zgz-01", "Teatro Principal Zaragoza"),
        _fixture_event("evt-demo-film-gra-exhibition-moon", "Granada Moon Cinema — Arte Nocturno", "Film", "Documentary", "Art Film", "Granada", "2026-08-11", "19:30", "rec-demo-film-gra-exhibition-moon", "Centro Jose Guerrero"),
        _fixture_event("evt-demo-film-ali-theatre-blue", "Alicante Blue Screen — Drama Mediterraneo", "Film", "Drama", "Mediterranean Cinema", "Alicante", "2026-08-12", "20:45", "rec-demo-film-ali-theatre-blue", "Teatro Principal Alicante"),
        _fixture_event("evt-demo-film-cor-comedy-atlantic", "A Coruna Atlantic Screen — Comedia Norte", "Film", "Comedy", "Atlantic Cinema", "A Coruña", "2026-08-13", "21:15", "rec-demo-film-cor-comedy-atlantic", "Teatro Colón"),
        # Family: 10
        _fixture_event("evt-demo-family-01", "Madrid Kids Lab — Robots Curiosos", "Family", "Kids", "Science", "Madrid", "2026-08-14", "11:00", "rec-demo-family-mad-01", "Museo Nacional de Ciencia"),
        _fixture_event("evt-demo-family-02", "Barcelona Circus Day — Pequenos Equilibristas", "Family", "Circus", "Circus", "Barcelona", "2026-08-15", "12:00", "rec-demo-family-bcn-01", "Ateneu Popular 9 Barris"),
        _fixture_event("evt-demo-family-03", "Valencia Ocean Kids — Exploradores Marinos", "Family", "Kids", "Aquarium", "Valencia", "2026-08-16", "10:30", "rec-demo-family-val-01", "Oceanografic"),
        _fixture_event("evt-demo-family-04", "Sevilla Magic Morning — Trucos de Patio", "Family", "Kids", "Magic", "Sevilla", "2026-08-17", "11:30", "rec-demo-family-sev-01", "Teatro Alameda"),
        _fixture_event("evt-demo-family-05", "Bilbao Family Expo — Inventos del Futuro", "Family", "Exhibition", "Science", "Bilbao", "2026-08-18", "12:00", "rec-demo-family-bio-01", "Azkuna Zentroa"),
        _fixture_event("evt-demo-family-06", "Malaga Mini Circus — Carpa de Verano", "Family", "Circus", "Circus", "Málaga", "2026-08-19", "18:00", "rec-demo-family-mal-01", "Auditorio Municipal Malaga"),
        _fixture_event("evt-demo-family-07", "Zaragoza Kids Theatre — Viaje Lunar", "Family", "Kids", "Theatre", "Zaragoza", "2026-08-20", "17:30", "rec-demo-family-zgz-01", "Teatro Arbolé"),
        _fixture_event("evt-demo-family-08", "Granada Family Stars — Planetario Vivo", "Family", "Exhibition", "Astronomy", "Granada", "2026-08-21", "11:00", "rec-demo-family-gra-01", "Parque de las Ciencias"),
        _fixture_event("evt-demo-family-09", "Alicante Kids Beach — Juegos del Mar", "Family", "Kids", "Outdoor", "Alicante", "2026-08-22", "10:00", "rec-demo-family-ali-01", "Playa del Postiguet"),
        _fixture_event("evt-demo-family-10", "A Coruna Circus Harbor — Carpa Atlantica", "Family", "Circus", "Circus", "A Coruña", "2026-08-23", "18:30", "rec-demo-family-cor-01", "Muelle de Trasatlanticos"),
        # Film: 10
        _fixture_event("evt-demo-film-01", "Madrid Cine Clasico — Noche Hitchcock", "Film", "Classic", "Thriller", "Madrid", "2026-08-24", "22:00", "rec-demo-film-mad-01", "Cineteca Madrid"),
        _fixture_event("evt-demo-film-02", "Barcelona Anime Night — Pantalla Grande", "Film", "Animation", "Anime", "Barcelona", "2026-08-25", "20:30", "rec-demo-film-bcn-01", "Phenomena Experience"),
        _fixture_event("evt-demo-film-03", "Valencia Sci-Fi Dock — Futuro Cercano", "Film", "Sci-Fi", "Science Fiction", "Valencia", "2026-08-26", "22:00", "rec-demo-film-val-01", "La Filmoteca Valencia"),
        _fixture_event("evt-demo-film-04", "Sevilla Cine de Verano — Comedia Bajo Estrellas", "Film", "Comedy", "Outdoor Cinema", "Sevilla", "2026-08-27", "22:15", "rec-demo-film-sev-01", "Jardines del Prado"),
        _fixture_event("evt-demo-film-05", "Bilbao Docs Live — Historias Urbanas", "Film", "Documentary", "Urban Stories", "Bilbao", "2026-08-28", "19:30", "rec-demo-film-bio-01", "Sala BBK"),
        _fixture_event("evt-demo-film-06", "Malaga Premiere Club — Cine Español", "Film", "Drama", "Spanish Cinema", "Málaga", "2026-08-29", "21:00", "rec-demo-film-mal-01", "Cine Albéniz"),
        _fixture_event("evt-demo-film-07", "Zaragoza Short Fest — Cortos Emergentes", "Film", "Shorts", "Festival", "Zaragoza", "2026-08-30", "20:00", "rec-demo-film-zgz-01", "Filmoteca Zaragoza"),
        _fixture_event("evt-demo-film-08", "Granada Cine Andalusi — Pantalla Historica", "Film", "Drama", "Historical", "Granada", "2026-08-31", "21:30", "rec-demo-film-gra-01", "Palacio de los Córdova"),
        _fixture_event("evt-demo-film-09", "Alicante Horror Dock — Sesion Medianoche", "Film", "Horror", "Midnight Screening", "Alicante", "2026-09-01", "23:45", "rec-demo-film-ali-01", "Cines Panoramis"),
        _fixture_event("evt-demo-film-10", "A Coruna Atlantic Cinema — Cine y Mar", "Film", "Documentary", "Ocean", "A Coruña", "2026-09-02", "20:30", "rec-demo-film-cor-01", "Domus"),
    ]
)


EXTRA_EVENT_COUNTS = {
    "Music": 14,
    "Sports": 14,
    "Arts & Theatre": 14,
    "Family": 13,
    "Film": 13,
}

EXTRA_EVENT_GENRES = {
    "Music": [
        ("Rock", "Alternative"),
        ("Pop", "Latin Pop"),
        ("Electronic", "House"),
        ("Urban", "Hip Hop"),
        ("Classical", "Chamber Music"),
    ],
    "Sports": [
        ("Football", "La Liga"),
        ("Basketball", "ACB"),
        ("Tennis", "Open"),
        ("Football", "Friendly"),
        ("Basketball", "Tournament"),
    ],
    "Arts & Theatre": [
        ("Theatre", "Drama"),
        ("Comedy", "Stand-up"),
        ("Musical", "Musical"),
        ("Exhibition", "Digital Art"),
        ("Theatre", "Experimental"),
    ],
    "Family": [
        ("Kids", "Science"),
        ("Circus", "Circus"),
        ("Kids", "Magic"),
        ("Exhibition", "Astronomy"),
        ("Kids", "Outdoor"),
    ],
    "Film": [
        ("Drama", "Spanish Cinema"),
        ("Sci-Fi", "Science Fiction"),
        ("Comedy", "Outdoor Cinema"),
        ("Documentary", "Urban Stories"),
        ("Animation", "Anime"),
    ],
}

EXTRA_EVENT_LABELS = {
    "Music": "Live Session",
    "Sports": "Match Day",
    "Arts & Theatre": "Stage Night",
    "Family": "Family Lab",
    "Film": "Cinema Club",
}

EXTRA_EVENT_SLUGS = {
    "Music": "music",
    "Sports": "sports",
    "Arts & Theatre": "arts",
    "Family": "family",
    "Film": "film",
}


def _build_extra_events() -> list[dict]:
    cities = list(CITY_META)
    start_date = date(2026, 9, 3)
    events = []
    day_offset = 0

    for segment, count in EXTRA_EVENT_COUNTS.items():
        slug = EXTRA_EVENT_SLUGS[segment]
        genres = EXTRA_EVENT_GENRES[segment]
        for index in range(1, count + 1):
            city = cities[(index + day_offset) % len(cities)]
            genre, subgenre = genres[(index - 1) % len(genres)]
            event_date = start_date + timedelta(days=day_offset)
            hour = ["10:30", "18:00", "19:30", "20:30", "21:30", "22:00"][(index - 1) % 6]
            event_id = f"evt-demo-extra-{slug}-{index:02d}"
            label = EXTRA_EVENT_LABELS[segment]
            events.append(
                _fixture_event(
                    event_id,
                    f"{city} {label} {index:02d} — {subgenre}",
                    segment,
                    genre,
                    subgenre,
                    city,
                    event_date.isoformat(),
                    hour,
                    f"rec-demo-extra-{slug}-{index:02d}",
                    f"{city} Demo Venue {index:02d}",
                )
            )
            day_offset += 1
    return events


EVENTS.extend(_build_extra_events())


class _EmulatorCredential(credentials.Base):
    """Stub credential — the Firestore emulator ignores auth."""

    def get_credential(self):
        from google.oauth2.credentials import Credentials as _GoogleCredentials
        return _GoogleCredentials(token="local-emulator-token")


def _wait_for_emulator(host_port: str, timeout: float = 60.0) -> None:
    host, port = host_port.rsplit(":", 1)
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, int(port)), timeout=2):
                return
        except OSError:
            time.sleep(1)
    raise RuntimeError(f"Firestore emulator not reachable at {host_port} after {timeout}s")


def main() -> None:
    host_port = os.environ.get("FIRESTORE_EMULATOR_HOST")
    if not host_port:
        raise RuntimeError(
            "FIRESTORE_EMULATOR_HOST is not set — this script only targets the emulator.",
        )
    _wait_for_emulator(host_port)

    firebase_admin.initialize_app(_EmulatorCredential(), {"projectId": PROJECT_ID})
    db = firestore.client()

    for event in EVENTS:
        doc = {**event}
        raw_utc = doc.get("fecha_utc")
        if isinstance(raw_utc, str):
            doc["fecha_utc"] = datetime.fromisoformat(raw_utc.replace("Z", "+00:00"))
        db.collection(COLLECTION).document(event["id"]).set(doc, merge=True)
        print(f"  ✓ {event['id']} — {event['nombre']}")

    print(f"Seeded {len(EVENTS)} events into '{COLLECTION}'.")

    if EVENTS_EXPORT_PATH:
        export_path = Path(EVENTS_EXPORT_PATH)
        export_path.parent.mkdir(parents=True, exist_ok=True)
        with export_path.open("w", encoding="utf-8") as handle:
            for event in EVENTS:
                handle.write(json.dumps(event, ensure_ascii=False) + "\n")
        print(f"Exported {len(EVENTS)} events to {export_path}.")


if __name__ == "__main__":
    main()
