name: cicd_terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_VAR_id_proyecto: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_repo_github: ${{ secrets.REPO_GITHUB }}
      TF_VAR_usuario_github: ${{ secrets.USUARIO_GITHUB }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
      TF_VAR_cors_origins: ${{ secrets.CORS_ORIGINS }}
      TF_VAR_portal_api_image: ${{ secrets.PORTAL_API_IMAGE }}

    steps:
      - name: Cargar repo
        uses: actions/checkout@v4

      - name: Autenticacion GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.TERRAFORM_CUENTA_SERVICIO }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve
